//? All widths, heights and radiuses are based on pixels
export const canvasWidth = 1400
export const cavnasHeight = 800

// Arbitrary number of vertex placement/graph build attempts.
// Algorithm will abort placement/build and throw an error on attempts overflow.
export const abortPlacementAttempts = 200
export const abortGraphBuildAttempts = 200

// How big station circle will be drawn on the canvas.
export const stationRadius = 20

// Defines closest possible placement of station next to the other station.
export const vertexExclusionRadius = stationRadius * 3

// Placement dimensions: canvas dimension padded by station radius.
export const xPlacementBound = canvasWidth - stationRadius
export const yPlacementBound = cavnasHeight - stationRadius

// Size of train shape.
export const trainRadius = 5

// Station names.
// Radiotelephony spelling alphabets in different languages/eras.
export const names = [
  'Alpha',
  'Bravo',
  'Charlie',
  'Delta',
  'Echo',
  'Foxtrot',
  'Hotel',
  'India',
  'Juliett',
  'Kilo',
  'Lima',
  'Mike',
  'November',
  'Oscar',
  'Papa',
  'Quebec',
  'Romeo',
  'Sierra',
  'Tango',
  'Uniform',
  'Victor',
  'Whiskey',
  'XRay',
  'Yankee',
  'Zebra',

  'Able',
  'Baker',
  'Dog',
  'Easy',
  'Fox',
  'George',
  'How',
  'Henry',
  'Item',
  'Italy',
  'Jig',
  'King',
  'Love',
  'Linda',
  'Nan',
  'Oboe',
  'Peter',
  'Queen',
  'Roger',
  'Rose',
  'Sugar',
  'Tare',
  'Uncle',
  'William',

  'Anton',
  'Berta',
  'Caeser',
  'Dora',
  'Emil',
  'Friedrich',
  'Gustav',
  'Heinrich',
  'Ida',
  'Josef',
  'Konrad',
  'Ludwig',
  'Martha',
  'Nordpol',
  'Otto',
  'Paula',
  'Quelle',
  'Richard',
  'Siegfried',
  'Toni',
  'Ulrich',
  'Viktor',
  'Wilhelm',
  'Xantippe',
  'Ypern',
  'Zeppelin',

  'Anna',
  'Boris',
  'Vasily',
  'Gregory',
  'Dmitri',
  'Elena',
  'Zinaida',
  'Ivan',
  'Konstantin',
  'Leonid',
  'Mikhail',
  'Nikolai',
  'Olga',
  'Pavel',
  'Roman',
  'Semyon',
  'Tatyana',
  'Ulyana',
  'Fyodor',
  'Khariton',
  'Tsaplya',
  'Chelovek',
  'Shura',
  'Yery',
  'Yuri',
  'Yakov',
]

export const trainNames = [
  'deserted',
  'aware',
  'vigorous',
  'third',
  'acoustic',
  'desperate',
  'troubled',
  'weary',
  'ordinary',
  'unbiased',
  'plant',
  'wide',
  'simple',
  'zany',
  'tiresome',
  'unaccountable',
  'cold',
  'disgusted',
  'level',
  'frightening',
  'thankful',
  'hysterical',
  'ratty',
  'royal',
  'vast',
  'melted',
  'gigantic',
  'dear',
  'fierce',
  'various',
  'heavenly',
  'flimsy',
  'pricey',
  'burly',
  'utter',
  'parched',
  'loving',
  'warlike',
  'ragged',
  'icky',
  'immense',
  'acrid',
  'informal',
  'sable',
  'jobless',
  'giant',
  'tiny',
  'thirsty',
  'gaping',
  'puzzled',
  'unknown',
  'swanky',
  'gifted',
  'bewildered',
  'greasy',
  'elfin',
  'technical',
  'embarrassed',
  'lying',
  'bashful',
  'overjoyed',
  'observant',
  'wretched',
  'evanescent',
  'soggy',
  'cautious',
  'rural',
  'wondrous',
  'careful',
  'tidy',
  'reminiscent',
  'suspicious',
  'visible',
  'delightful',
  'silent',
  'hollow',
  'anxious',
  'neat',
  'venomous',
  'misty',
  'breezy',
  'quickest',
  'daffy',
  'far',
  'freezing',
  'synonymous',
  'defiant',
  'exuberant',
  'intelligent',
  'dirty',
  'dazzling',
  'coherent',
  'threatening',
  'rampant',
  'economic',
  'madly',
  'uneven',
  'abaft',
  'hateful',
  'acid',
]
